set serveroutput on;
set pagesize 1000;
set linesize 1000;

-- drop partition temp views
DROP MATERIALIZED VIEW PERFORMANCE_AGGREGATE_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_CPU_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_DISK_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_DISK_TOTAL_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_ESX3_WORKLOAD_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_FSCAP_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_LPAR_WORKLOAD_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_NETWORK_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_NRM_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_PSINFO_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_VXVOL_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_WHO_PAR
/
DROP MATERIALIZED VIEW PERFORMANCE_SAMPLE_PAR
/

DROP MATERIALIZED VIEW VMWP_AGGREGATE_PAR
/
DROP MATERIALIZED VIEW VMWP_CLUSTER_PAR
/
DROP MATERIALIZED VIEW VMWP_DATASTORE_USAGE_PAR
/
DROP MATERIALIZED VIEW VMWP_DATASTORE_VM_USAGE_PAR
/
DROP MATERIALIZED VIEW VMWP_DISK_RATE_PAR
/
DROP MATERIALIZED VIEW VMWP_ENTITLEMENT_PAR
/
DROP MATERIALIZED VIEW VMWP_HOST_CPU_PAR
/
DROP MATERIALIZED VIEW VMWP_HOST_DISK_IO_PAR
/
DROP MATERIALIZED VIEW VMWP_HOST_DISK_IO_ADV_PAR
/
DROP MATERIALIZED VIEW VMWP_HOST_NETWORK_PAR
/
DROP MATERIALIZED VIEW VMWP_HOST_POWER_STATE_PAR
/
DROP MATERIALIZED VIEW VMWP_MEM_PAR
/
DROP MATERIALIZED VIEW VMWP_MEM_ADVANCED_PAR
/
DROP MATERIALIZED VIEW VMWP_NETWORK_RATE_PAR
/
DROP MATERIALIZED VIEW VMWP_VM_CPU_PAR
/
DROP MATERIALIZED VIEW VMWP_VM_DISK_IO_PAR
/
DROP MATERIALIZED VIEW VMWP_VM_NETWORK_PAR
/
DROP MATERIALIZED VIEW VMWP_VM_POWER_STATE_PAR
/
DROP MATERIALIZED VIEW VMWP_VM_STORAGE_USAGE_PAR
/
DROP MATERIALIZED VIEW VMWP_VM_VCPU_PAR
/
DROP MATERIALIZED VIEW VMWP_WATTS_PAR
/
DROP MATERIALIZED VIEW VMWP_SAMPLE_PAR
/

DROP MATERIALIZED VIEW NET_DP_PING_PAR
/
DROP MATERIALIZED VIEW NET_DP_PORT_PAR
/
DROP MATERIALIZED VIEW NET_DP_SAMPLE_PAR
/


-- drop partition temp tables

DROP TABLE PERFORMANCE_AGGREGATE_PAR
/
DROP TABLE PERFORMANCE_CPU_PAR
/
DROP TABLE PERFORMANCE_DISK_PAR
/
DROP TABLE PERFORMANCE_DISK_TOTAL_PAR
/
DROP TABLE PERFORMANCE_ESX3_WORKLOAD_PAR
/
DROP TABLE PERFORMANCE_FSCAP_PAR
/
DROP TABLE PERFORMANCE_LPAR_WORKLOAD_PAR
/
DROP TABLE PERFORMANCE_NETWORK_PAR
/
DROP TABLE PERFORMANCE_NRM_PAR
/
DROP TABLE PERFORMANCE_PSINFO_PAR
/
DROP TABLE PERFORMANCE_VXVOL_PAR
/
DROP TABLE PERFORMANCE_WHO_PAR
/
DROP TABLE PERFORMANCE_SAMPLE_PAR
/
DROP TABLE ERDC_INT_DATA_PAR
/
DROP TABLE ERDC_DECIMAL_DATA_PAR
/
DROP TABLE ERDC_STRING_DATA_PAR
/
DROP TABLE RANGED_OBJECT_VALUE_PAR
/
-- New tables in up.time 6.0 --
DROP TABLE VMWP_AGGREGATE_PAR
/
DROP TABLE VMWP_CLUSTER_PAR
/
DROP TABLE VMWP_DATASTORE_USAGE_PAR
/
DROP TABLE VMWP_DATASTORE_VM_USAGE_PAR
/
DROP TABLE VMWP_DISK_RATE_PAR
/
DROP TABLE VMWP_ENTITLEMENT_PAR
/
DROP TABLE VMWP_HOST_CPU_PAR
/
DROP TABLE VMWP_HOST_DISK_IO_PAR
/
DROP TABLE VMWP_HOST_DISK_IO_ADV_PAR
/
DROP TABLE VMWP_HOST_NETWORK_PAR
/
DROP TABLE VMWP_HOST_POWER_STATE_PAR
/
DROP TABLE VMWP_MEM_PAR
/
DROP TABLE VMWP_MEM_ADVANCED_PAR
/
DROP TABLE VMWP_NETWORK_RATE_PAR
/
DROP TABLE VMWP_VM_CPU_PAR
/
DROP TABLE VMWP_VM_DISK_IO_PAR
/
DROP TABLE VMWP_VM_NETWORK_PAR
/
DROP TABLE VMWP_VM_POWER_STATE_PAR
/
DROP TABLE VMWP_VM_STORAGE_USAGE_PAR
/
DROP TABLE VMWP_VM_VCPU_PAR
/
DROP TABLE VMWP_WATTS_PAR
/
DROP TABLE VMWP_SAMPLE_PAR
/
-- New tables in up.time 7.0 --
DROP TABLE NET_DP_PING_PAR
/
DROP TABLE NET_DP_PORT_PAR
/
DROP TABLE NET_DP_SAMPLE_PAR
/
