-- up.time 6.x Tables

CREATE TABLE VMWP_AGGREGATE_PAR (
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU_RESERVATION" NUMBER(20),
"CPU_USAGE" NUMBER(20),
"CPU_TOTAL" NUMBER(20),
"DISK_USAGE" NUMBER(20),
"MEMORY_RESERVATION" NUMBER(20),
"MEMORY_USAGE" NUMBER(20),
"MEMORY_TOTAL" NUMBER(20),
"NETWORK_USAGE" NUMBER(20),
CONSTRAINT "FK_VM_AGG" FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_AGG)
/

CREATE TABLE "VMWP_CLUSTER_PAR" (
"SAMPLE_ID" NUMBER(20) NOT NULL,
"FAILOVER" NUMBER(20),
CONSTRAINT "FK_CLUSTER"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_CLUSTER)
/

CREATE TABLE "VMWP_DATASTORE_USAGE_PAR" (
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CAPACITY" NUMBER(20),
"PROVISIONED" NUMBER(20),
"USAGE_TOTAL" NUMBER(20),
"USAGE_VM_DISK" NUMBER(20),
"USAGE_SNAPSHOT" NUMBER(20),
"USAGE_SWAP" NUMBER(20),
"USAGE_OTHER_VM" NUMBER(20),
"USAGE_OTHER" NUMBER(20),
CONSTRAINT "FK_DATASTORE_USAGE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_DATASTORE_USAGE)
/

CREATE TABLE "VMWP_DATASTORE_VM_USAGE_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"VIRTUAL_MACHINE_ID" NUMBER(20),
"USAGE_TOTAL" NUMBER(20),
CONSTRAINT "FK_DATASTORE_VM_USAGE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_DATASTORE_VM_USAGE)
/

CREATE TABLE "VMWP_DISK_RATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"READ_RATE" NUMBER(20),
"WRITE_RATE" NUMBER(20),
CONSTRAINT "FK_DISK_RATE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_DISK_RATE)
/

CREATE TABLE "VMWP_ENTITLEMENT_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU" NUMBER(20),
"MEMORY" NUMBER(20),
CONSTRAINT "FK_ENTITLEMENT"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_ENTITLEMENT)
/

CREATE TABLE "VMWP_HOST_CPU_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU_ID" NUMBER(20),
"CPU_PERCENT_USAGE" NUMBER(20),
CONSTRAINT "FK_HOST_CPU"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_CPU)
/

CREATE TABLE "VMWP_HOST_DISK_IO_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"DISK_ID" VARCHAR2(255),
"READ_LATENCY" NUMBER(20),
"WRITE_LATENCY" NUMBER(20),
"TOTAL_LATENCY" NUMBER(20),
"READ_RATE" NUMBER(20),
"WRITE_RATE" NUMBER(20),
CONSTRAINT "FK_HOST_DISK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_DISK)
/

CREATE TABLE "VMWP_HOST_DISK_IO_ADV_PAR" (
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"DISK_ID" VARCHAR2(255),
"BUS_RESETS" NUMBER(20),
"COMMANDS_ABORTED" NUMBER(20),
"DEVICE_LATENCY" NUMBER(20),
"DEVICE_READ_LATENCY" NUMBER(20),
"DEVICE_WRITE_LATENCY" NUMBER(20),
"KERNEL_LATENCY" NUMBER(20),
"KERNEL_READ_LATENCY" NUMBER(20),
"KERNEL_WRITE_LATENCY" NUMBER(20),
"QUEUE_LATENCY" NUMBER(20),
"QUEUE_READ_LATENCY" NUMBER(20),
"QUEUE_WRITE_LATENCY" NUMBER(20),
"READ_COUNT" NUMBER(20),
"WRITE_COUNT" NUMBER(20),
CONSTRAINT "FK_HOST_DISK_ADV"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_DISK_ADV)
/

CREATE TABLE "VMWP_HOST_NETWORK_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"NIC_ID" VARCHAR2(255),
"RECEIVE_RATE" NUMBER(20),
"RECEIVE_DROPPED" NUMBER(20),
"TRANSMIT_RATE" NUMBER(20),
"TRANSMIT_DROPPED" NUMBER(20),
CONSTRAINT "FK_HOST_NETWORK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_NETWORK)
/

CREATE TABLE "VMWP_HOST_POWER_STATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"POWERED_ON" NUMBER(10),
"POWERED_OFF" NUMBER(10),
"MAINTENANCE" NUMBER(10),
"STANDBY" NUMBER(10),
"UNKNOWN" NUMBER(10),
CONSTRAINT "FK_HOST_POWER"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_HOST_POWER)
/

CREATE TABLE "VMWP_MEM_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"ACTIVE" NUMBER(20),
"BALLOONED" NUMBER(20),
"GRANTED" NUMBER(20),
CONSTRAINT "FK_VM_MEM"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_MEM)
/

CREATE TABLE "VMWP_MEM_ADVANCED_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"OVERHEAD" NUMBER(20),
"SHARED" NUMBER(20),
"SHARED_COMMON" NUMBER(20),
"SWAP_RATE_IN" NUMBER(20),
"SWAP_RATE_OUT" NUMBER(20),
"SWAP_USED" NUMBER(20),
"ZERO" NUMBER(20),
CONSTRAINT "FK_VM_MEM_ADV"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_MEM_ADV)
/

CREATE TABLE "VMWP_NETWORK_RATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"RECEIVE_RATE" NUMBER(20),
"TRANSMIT_RATE" NUMBER(20),
CONSTRAINT "FK_NETWORK_RATE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_NETWORK_RATE)
/

CREATE TABLE "VMWP_VM_CPU_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"READY" NUMBER(20),
"WAIT" NUMBER(20),
"CPU_PERCENT_USAGE" NUMBER(20),
CONSTRAINT "FK_VM_CPU"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_CPU)
/

CREATE TABLE "VMWP_VM_DISK_IO_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"DISK_ID" VARCHAR2(255),
"BUS_RESETS" NUMBER(20),
"COMMANDS_ABORTED" NUMBER(20),
"READ_COUNT" NUMBER(20),
"READ_RATE" NUMBER(20),
"WRITE_COUNT" NUMBER(20),
"WRITE_RATE" NUMBER(20),
CONSTRAINT "FK_VM_DISK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_VM_DISK)
/

CREATE TABLE "VMWP_VM_NETWORK_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"NIC_ID" VARCHAR2(255),
"RECEIVE_RATE" NUMBER(20),
"TRANSMIT_RATE" NUMBER(20),
CONSTRAINT "FK_VM_NETWORK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_VM_NETWORK)
/

CREATE TABLE "VMWP_VM_POWER_STATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"POWERED_ON" NUMBER(10),
"POWERED_OFF" NUMBER(10),
"SUSPENDED" NUMBER(10),
CONSTRAINT "FK_VM_POWER"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_POWER)
/

CREATE TABLE "VMWP_VM_STORAGE_USAGE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"PROVISIONED" NUMBER(20),
"DISK" NUMBER(20),
"SNAPSHOT" NUMBER(20),
"SWAP" NUMBER(20),
"OTHER" NUMBER(20),
CONSTRAINT "FK_VM_STORAGE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_STORAGE)
/

CREATE TABLE "VMWP_VM_VCPU_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU_ID" NUMBER(20),
"CPU_USAGE" NUMBER(20),
"SYSTEM" NUMBER(20),
"WAIT" NUMBER(20),
"USED" NUMBER(20),
CONSTRAINT "FK_VM_VCPU"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_VM_VCPU)
/

CREATE TABLE "VMWP_WATTS_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"WATTS" NUMBER(20),
CONSTRAINT "FK_VM_WATTS"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_WATTS)
/



-- up.time 7.0 Tables

CREATE TABLE "NET_DP_PING_PAR" ( 
"ID" NUMBER(20),
"AVERAGE_TIME" FLOAT(126),
"PERCENT_LOSS" FLOAT(126),
"SAMPLE_ID" NUMBER(20) NOT NULL,
CONSTRAINT "FK_NET_DEV_PING"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES NET_DEVICE_PERF_SAMPLE ("ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_NET_DEV_PING)
/

CREATE TABLE "NET_DP_PORT_PAR" ( 
"ID" NUMBER(20),
"IF_INDEX" NUMBER(20),
"IF_OPER_STATUS" NUMBER(20),
"KBPS_IN_RATE" NUMBER(20),
"KBPS_OUT_RATE" NUMBER(20),
"KBPS_TOTAL_RATE" NUMBER(20),
"DISCARDS_IN_RATE" NUMBER(20),
"DISCARDS_OUT_RATE" NUMBER(20),
"DISCARDS_TOTAL_RATE" NUMBER(20),
"ERRORS_IN_RATE" NUMBER(20),
"ERRORS_OUT_RATE" NUMBER(20),
"ERRORS_TOTAL_RATE" NUMBER(20),
"USAGE_IN_PERCENT" NUMBER(10),
"USAGE_OUT_PERCENT" NUMBER(10),
"USAGE_PERCENT" NUMBER(10),
"SAMPLE_ID" NUMBER(20) NOT NULL,
CONSTRAINT "FK_NET_DEV_PORT"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES NET_DEVICE_PERF_SAMPLE ("ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_NET_DEV_PORT)
/
