-- up.time 5.x Tables

------------------------------------
-- Start of PERFORMANCE_AGGREGATE --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_AGGREGATE_PAR (
"SAMPLE_ID" NUMBER(20) NOT NULL, 
"CPU_USR" FLOAT(126), 
"CPU_SYS" FLOAT(126), 
"CPU_WIO" FLOAT(126), 
"FREE_MEM" FLOAT(126), 
"FREE_SWAP" FLOAT(126), 
"RUN_QUEUE" FLOAT(126), 
"RUN_OCC" FLOAT(126), 
"READ_CACHE" FLOAT(126), 
"WRITE_CACHE" FLOAT(126), 
"PG_OUT_SEC" FLOAT(126), 
"PPG_OUT_SEC" FLOAT(126), 
"PG_FREE_SEC" FLOAT(126), 
"PG_SCAN_SEC" FLOAT(126), 
"ATCH_SEC" FLOAT(126), 
"PG_IN_SEC" FLOAT(126), 
"PPG_IN_SEC" FLOAT(126), 
"PFLT_SEC" FLOAT(126), 
"VFLT_SEC" FLOAT(126), 
"SLOCK_SEC" FLOAT(126), 
"NUM_PROCS" NUMBER(20), 
"PROC_READ" FLOAT(126), 
"PROC_WRITE" FLOAT(126), 
"PROC_BLOCK" FLOAT(126), 
"DNLC" FLOAT(126), 
"FORK_SEC" FLOAT(126), 
"EXEC_SEC" FLOAT(126), 
"TCP_RETRANS" NUMBER(20), 
"WORST_DISK_USAGE" NUMBER(20), 
"WORST_DISK_BUSY" NUMBER(20), 
"USED_SWAP_PERCENT" NUMBER(20), 
PRIMARY KEY (SAMPLE_ID) VALIDATE, 
CONSTRAINT FK_AGGREGATE FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_AGGREGATE)
/

------------------------------------
-- Start of PERFORMANCE_CPU --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_CPU_PAR( 
"ID" NUMBER(20), 
"CPU_ID" NUMBER(20), 
"CPU_USR" NUMBER(20), 
"CPU_SYS" NUMBER(20), 
"CPU_WIO" NUMBER(20), 
"XCAL" NUMBER(20), 
"INTR" NUMBER(20), 
"SMTX" NUMBER(20), 
"MINF" FLOAT(126), 
"MJF" FLOAT(126), 
"ITHR" FLOAT(126), 
"CSW" FLOAT(126), 
"ICSW" FLOAT(126), 
"MIGR" FLOAT(126), 
"SRW" FLOAT(126), 
"SYSCL" FLOAT(126), 
"IDLE" FLOAT(126), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE,
CONSTRAINT FK_CPU FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_CPU)
/

------------------------------------
-- Start of PERFORMANCE_DISK --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_DISK_PAR ( 
"ID" NUMBER(20), 
"DISK_NAME" VARCHAR2(255), 
"PCT_TIME_BUSY" NUMBER(20), 
"AVG_QUEUE_REQ" NUMBER(20), 
"RW_SEC" NUMBER(20), 
"BLOCKS_SEC" NUMBER(20), 
"AVG_WAIT_TIME" NUMBER(20), 
"AVG_SERV_TIME" NUMBER(20), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE ,
CONSTRAINT FK_DISK FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_DISK)
/

------------------------------------
-- Start of PERFORMANCE_DISK_TOTAL --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_DISK_TOTAL_PAR (
"SAMPLE_ID" NUMBER(20) NOT NULL, 
"PCT_TIME_BUSY" NUMBER(20), 
"AVG_QUEUE_REQ" NUMBER(20), 
"RW_SEC" NUMBER(20), 
"BLOCKS_SEC" NUMBER(20), 
"AVG_WAIT_TIME" NUMBER(20), 
"AVG_SERV_TIME" NUMBER(20), 
PRIMARY KEY ("SAMPLE_ID") VALIDATE,
CONSTRAINT FK_DISK_TOTAL FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE
) 
PARTITION BY REFERENCE (FK_DISK_TOTAL)
/

------------------------------------
-- Start of PERFORMANCE_ESX3_WORKLOAD --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_ESX3_WORKLOAD_PAR ( 
"ID" NUMBER(20), 
"UUID" VARCHAR2(255), 
"INSTANCE_NAME" VARCHAR2(255), 
"CPU_USAGE_MHZ" NUMBER(20), 
"MEMORY" NUMBER(20), 
"DISK_IO_RATE" NUMBER(20), 
"NETWORK_IO_RATE" NUMBER(20), 
"PERCENT_READY" FLOAT(126), 
"PERCENT_USED" FLOAT(126), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE ,
CONSTRAINT FK_ESX3 FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_ESX3)
/

------------------------------------
-- Start of PERFORMANCE_FSCAP --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_FSCAP_PAR ( 
"ID" NUMBER(20), 
"FILESYSTEM" VARCHAR2(255), 
"TOTAL_SIZE" NUMBER(20), 
"SPACE_USED" NUMBER(20), 
"SPACE_AVAIL" NUMBER(20), 
"PERCENT_USED" NUMBER(20), 
"MOUNT_POINT" VARCHAR2(255), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE,
CONSTRAINT FK_FSCAP FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_FSCAP)
/

------------------------------------
-- Start of PERFORMANCE_LPAR_WORKLOAD --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_LPAR_WORKLOAD_PAR ( 
"ID" NUMBER(20), 
"LPAR_ID" NUMBER(20), 
"INSTANCE_NAME" VARCHAR2(255), 
"ENTITLEMENT" FLOAT(126), 
"CPU_USAGE" FLOAT(126), 
"USED_MEMORY" NUMBER(20), 
"NETWORK_IO_RATE" NUMBER(20), 
"DISK_IO_RATE" NUMBER(20), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE, 
CONSTRAINT FK_LPAR FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_LPAR)
/

------------------------------------
-- Start of PERFORMANCE_NETWORK --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_NETWORK_PAR ( 
"ID" NUMBER(20), 
"IFACE_NAME" VARCHAR2(255), 
"IN_BYTES" NUMBER(20), 
"OUT_BYTES" NUMBER(20), 
"COLLISIONS" NUMBER(20), 
"IN_ERRORS" NUMBER(20), 
"OUT_ERRORS" NUMBER(20), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE, 
CONSTRAINT FK_NETWORK FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_NETWORK)
/

------------------------------------
-- Start of PERFORMANCE_NRM --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_NRM_PAR ( 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
"WORK_TO_DO" NUMBER(20), 
"AVAILABLE_DISK" NUMBER(20), 
"DS_THREAD_USAGE" NUMBER(20), 
"ALLOCATED_SERVER_PROCS" NUMBER(20), 
"AVAILABLE_SERVER_PROCS" NUMBER(20), 
"PACKET_RECEIVE_BUFFERS" NUMBER(20), 
"AVAILABLE_ECBS" NUMBER(20), 
"LAN_TRAFFIC" NUMBER(20), 
"CONNECTION_USAGE" NUMBER(20), 
"DISK_THROUGHPUT" NUMBER(20), 
"ABENDED_THREAD_COUNT" NUMBER(20), 
PRIMARY KEY ("SAMPLE_ID") VALIDATE, 
CONSTRAINT FK_NRM FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_NRM)
/

------------------------------------
-- Start of PERFORMANCE_PSINFO --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_PSINFO_PAR ( 
"ID" NUMBER(20), 
"PID" NUMBER(20), 
"PPID" NUMBER(20), 
"PS_UID" VARCHAR2(255), 
"GID" VARCHAR2(255), 
"MEM_USED" NUMBER(20), 
"RSS" NUMBER(20), 
"CPU_USAGE" FLOAT(126), 
"MEMORY_USAGE" FLOAT(126), 
"USER_CPU_TIME" NUMBER(20), 
"SYS_CPU_TIME" NUMBER(20), 
"START_TIME" TIMESTAMP(6), 
"PROC_NAME" VARCHAR2(255), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE, 
CONSTRAINT FK_PSINFO FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_PSINFO)
/

------------------------------------
-- Start of PERFORMANCE_VXVOL --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_VXVOL_PAR ( 
"ID" NUMBER(20), 
"DG" VARCHAR2(255), 
"VOL" VARCHAR2(255), 
"RD_OPS" NUMBER(20), 
"WR_OPS" NUMBER(20), 
"RD_BLKS" NUMBER(20), 
"WR_BLKS" NUMBER(20), 
"AVG_RD" NUMBER(20), 
"AVG_WR" NUMBER(20), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE, 
CONSTRAINT FK_VXVOL FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_VXVOL)
/

------------------------------------
-- Start of PERFORMANCE_WHO --
------------------------------------
-- With Reference Partitioning --
CREATE TABLE PERFORMANCE_WHO_PAR ( 
"ID" NUMBER(20), 
"USERNAME" VARCHAR2(255), 
"SESSION_COUNT" NUMBER(20), 
"SAMPLE_ID" NUMBER(20) NOT NULL, 
PRIMARY KEY ("ID") VALIDATE, 
CONSTRAINT FK_WHO FOREIGN KEY (SAMPLE_ID) 
  REFERENCES PERFORMANCE_SAMPLE (ID) VALIDATE 
)
PARTITION BY REFERENCE (FK_WHO)
/


-- up.time 6.x Tables


CREATE TABLE VMWP_AGGREGATE_PAR (
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU_RESERVATION" NUMBER(20),
"CPU_USAGE" NUMBER(20),
"CPU_TOTAL" NUMBER(20),
"DISK_USAGE" NUMBER(20),
"MEMORY_RESERVATION" NUMBER(20),
"MEMORY_USAGE" NUMBER(20),
"MEMORY_TOTAL" NUMBER(20),
"NETWORK_USAGE" NUMBER(20),
CONSTRAINT "FK_VM_AGG" FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_AGG)
/

CREATE TABLE "VMWP_CLUSTER_PAR" (
"SAMPLE_ID" NUMBER(20) NOT NULL,
"FAILOVER" NUMBER(20),
CONSTRAINT "FK_CLUSTER"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_CLUSTER)
/

CREATE TABLE "VMWP_DATASTORE_USAGE_PAR" (
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CAPACITY" NUMBER(20),
"PROVISIONED" NUMBER(20),
"USAGE_TOTAL" NUMBER(20),
"USAGE_VM_DISK" NUMBER(20),
"USAGE_SNAPSHOT" NUMBER(20),
"USAGE_SWAP" NUMBER(20),
"USAGE_OTHER_VM" NUMBER(20),
"USAGE_OTHER" NUMBER(20),
CONSTRAINT "FK_DATASTORE_USAGE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_DATASTORE_USAGE)
/

CREATE TABLE "VMWP_DATASTORE_VM_USAGE_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"VIRTUAL_MACHINE_ID" NUMBER(20),
"USAGE_TOTAL" NUMBER(20),
CONSTRAINT "FK_DATASTORE_VM_USAGE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_DATASTORE_VM_USAGE)
/

CREATE TABLE "VMWP_DISK_RATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"READ_RATE" NUMBER(20),
"WRITE_RATE" NUMBER(20),
CONSTRAINT "FK_DISK_RATE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_DISK_RATE)
/

CREATE TABLE "VMWP_ENTITLEMENT_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU" NUMBER(20),
"MEMORY" NUMBER(20),
CONSTRAINT "FK_ENTITLEMENT"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_ENTITLEMENT)
/

CREATE TABLE "VMWP_HOST_CPU_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU_ID" NUMBER(20),
"CPU_PERCENT_USAGE" NUMBER(20),
CONSTRAINT "FK_HOST_CPU"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_CPU)
/

CREATE TABLE "VMWP_HOST_DISK_IO_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"DISK_ID" VARCHAR2(255),
"READ_LATENCY" NUMBER(20),
"WRITE_LATENCY" NUMBER(20),
"TOTAL_LATENCY" NUMBER(20),
"READ_RATE" NUMBER(20),
"WRITE_RATE" NUMBER(20),
CONSTRAINT "FK_HOST_DISK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_DISK)
/

CREATE TABLE "VMWP_HOST_DISK_IO_ADV_PAR" (
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"DISK_ID" VARCHAR2(255),
"BUS_RESETS" NUMBER(20),
"COMMANDS_ABORTED" NUMBER(20),
"DEVICE_LATENCY" NUMBER(20),
"DEVICE_READ_LATENCY" NUMBER(20),
"DEVICE_WRITE_LATENCY" NUMBER(20),
"KERNEL_LATENCY" NUMBER(20),
"KERNEL_READ_LATENCY" NUMBER(20),
"KERNEL_WRITE_LATENCY" NUMBER(20),
"QUEUE_LATENCY" NUMBER(20),
"QUEUE_READ_LATENCY" NUMBER(20),
"QUEUE_WRITE_LATENCY" NUMBER(20),
"READ_COUNT" NUMBER(20),
"WRITE_COUNT" NUMBER(20),
CONSTRAINT "FK_HOST_DISK_ADV"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_DISK_ADV)
/

CREATE TABLE "VMWP_HOST_NETWORK_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"NIC_ID" VARCHAR2(255),
"RECEIVE_RATE" NUMBER(20),
"RECEIVE_DROPPED" NUMBER(20),
"TRANSMIT_RATE" NUMBER(20),
"TRANSMIT_DROPPED" NUMBER(20),
CONSTRAINT "FK_HOST_NETWORK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_HOST_NETWORK)
/

CREATE TABLE "VMWP_HOST_POWER_STATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"POWERED_ON" NUMBER(10),
"POWERED_OFF" NUMBER(10),
"MAINTENANCE" NUMBER(10),
"STANDBY" NUMBER(10),
"UNKNOWN" NUMBER(10),
CONSTRAINT "FK_HOST_POWER"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_HOST_POWER)
/

CREATE TABLE "VMWP_MEM_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"ACTIVE" NUMBER(20),
"BALLOONED" NUMBER(20),
"GRANTED" NUMBER(20),
CONSTRAINT "FK_VM_MEM"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_MEM)
/

CREATE TABLE "VMWP_MEM_ADVANCED_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"OVERHEAD" NUMBER(20),
"SHARED" NUMBER(20),
"SHARED_COMMON" NUMBER(20),
"SWAP_RATE_IN" NUMBER(20),
"SWAP_RATE_OUT" NUMBER(20),
"SWAP_USED" NUMBER(20),
"ZERO" NUMBER(20),
CONSTRAINT "FK_VM_MEM_ADV"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_MEM_ADV)
/

CREATE TABLE "VMWP_NETWORK_RATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"RECEIVE_RATE" NUMBER(20),
"TRANSMIT_RATE" NUMBER(20),
CONSTRAINT "FK_NETWORK_RATE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_NETWORK_RATE)
/

CREATE TABLE "VMWP_VM_CPU_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"READY" NUMBER(20),
"WAIT" NUMBER(20),
"CPU_PERCENT_USAGE" NUMBER(20),
CONSTRAINT "FK_VM_CPU"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_CPU)
/

CREATE TABLE "VMWP_VM_DISK_IO_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"DISK_ID" VARCHAR2(255),
"BUS_RESETS" NUMBER(20),
"COMMANDS_ABORTED" NUMBER(20),
"READ_COUNT" NUMBER(20),
"READ_RATE" NUMBER(20),
"WRITE_COUNT" NUMBER(20),
"WRITE_RATE" NUMBER(20),
CONSTRAINT "FK_VM_DISK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_VM_DISK)
/

CREATE TABLE "VMWP_VM_NETWORK_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"NIC_ID" VARCHAR2(255),
"RECEIVE_RATE" NUMBER(20),
"TRANSMIT_RATE" NUMBER(20),
CONSTRAINT "FK_VM_NETWORK"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_VM_NETWORK)
/

CREATE TABLE "VMWP_VM_POWER_STATE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"POWERED_ON" NUMBER(10),
"POWERED_OFF" NUMBER(10),
"SUSPENDED" NUMBER(10),
CONSTRAINT "FK_VM_POWER"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_POWER)
/

CREATE TABLE "VMWP_VM_STORAGE_USAGE_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"PROVISIONED" NUMBER(20),
"DISK" NUMBER(20),
"SNAPSHOT" NUMBER(20),
"SWAP" NUMBER(20),
"OTHER" NUMBER(20),
CONSTRAINT "FK_VM_STORAGE"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_STORAGE)
/

CREATE TABLE "VMWP_VM_VCPU_PAR" ( 
"ID" NUMBER(20),
"SAMPLE_ID" NUMBER(20) NOT NULL,
"CPU_ID" NUMBER(20),
"CPU_USAGE" NUMBER(20),
"SYSTEM" NUMBER(20),
"WAIT" NUMBER(20),
"USED" NUMBER(20),
CONSTRAINT "FK_VM_VCPU"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_VM_VCPU)
/

CREATE TABLE "VMWP_WATTS_PAR" ( 
"SAMPLE_ID" NUMBER(20) NOT NULL,
"WATTS" NUMBER(20),
CONSTRAINT "FK_VM_WATTS"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES VMWARE_PERF_SAMPLE ("SAMPLE_ID") VALIDATE ,
PRIMARY KEY ("SAMPLE_ID") VALIDATE )
PARTITION BY REFERENCE (FK_VM_WATTS)
/



-- up.time 7.0 Tables

CREATE TABLE "NET_DP_PING_PAR" ( 
"ID" NUMBER(20),
"AVERAGE_TIME" FLOAT(126),
"PERCENT_LOSS" FLOAT(126),
"SAMPLE_ID" NUMBER(20) NOT NULL,
CONSTRAINT "FK_NET_DEV_PING"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES NET_DEVICE_PERF_SAMPLE ("ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_NET_DEV_PING)
/

CREATE TABLE "NET_DP_PORT_PAR" ( 
"ID" NUMBER(20),
"IF_INDEX" NUMBER(20),
"IF_OPER_STATUS" NUMBER(20),
"KBPS_IN_RATE" NUMBER(20),
"KBPS_OUT_RATE" NUMBER(20),
"KBPS_TOTAL_RATE" NUMBER(20),
"DISCARDS_IN_RATE" NUMBER(20),
"DISCARDS_OUT_RATE" NUMBER(20),
"DISCARDS_TOTAL_RATE" NUMBER(20),
"ERRORS_IN_RATE" NUMBER(20),
"ERRORS_OUT_RATE" NUMBER(20),
"ERRORS_TOTAL_RATE" NUMBER(20),
"USAGE_IN_PERCENT" NUMBER(10),
"USAGE_OUT_PERCENT" NUMBER(10),
"USAGE_PERCENT" NUMBER(10),
"SAMPLE_ID" NUMBER(20) NOT NULL,
CONSTRAINT "FK_NET_DEV_PORT"
FOREIGN KEY ("SAMPLE_ID")
REFERENCES NET_DEVICE_PERF_SAMPLE ("ID") VALIDATE ,
PRIMARY KEY (ID, SAMPLE_ID) VALIDATE )
PARTITION BY REFERENCE (FK_NET_DEV_PORT)
/
